### ISSUE TITLE
Does not build on android, flutter 3.0.2

### ISSUE THREAD

**Issue by mp035** [kechankrisna/webcontent_converter#13]
Hi, Thanks for such a great package!  When trying to build on flutter 3.0.2 I get the following error:

```
e: /home/XXXXXXXXXX/app/custom_packages/webcontent_converter/android/src/main/kotlin/app/mylekha/webcontent_converter/FLNativeViewFactory.kt: (10, 1): Class 'FLNativeViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: /home/XXXXXXXXXX/app/custom_packages/webcontent_converter/android/src/main/kotlin/app/mylekha/webcontent_converter/FLNativeViewFactory.kt: (11, 5): 'create' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webcontent_converter:compileDebugKotlin'.
> Compilation error. See log for more details
```
There seems to be a change to the constructor signature, so I have created the following patch (also attached):

```
diff --git a/android/src/main/kotlin/app/mylekha/webcontent_converter/FLNativeViewFactory.kt b/android/src/main/kotlin/app/mylekha/webcontent_converter/FLNativeViewFactory.kt
index 39acada..179df38 100644
--- a/android/src/main/kotlin/app/mylekha/webcontent_converter/FLNativeViewFactory.kt
+++ b/android/src/main/kotlin/app/mylekha/webcontent_converter/FLNativeViewFactory.kt
@@ -8,9 +8,9 @@ import io.flutter.plugin.platform.PlatformView
 import io.flutter.plugin.platform.PlatformViewFactory
 
 class FLNativeViewFactory : PlatformViewFactory(StandardMessageCodec.INSTANCE) {
-    override fun create(context: Context, viewId: Int, args: Any?): PlatformView {
+    override fun create(context: Context?, viewId: Int, args: Any?): PlatformView {
         val creationParams = args as Map<String?, Any?>?
-        return FLNativeView(context, viewId, creationParams)
+        return FLNativeView(context as Context, viewId, creationParams)
     }
 }
```
[mp035.zip](https://github.com/kechankrisna/webcontent_converter/files/8953837/mp035.zip)

Please note that I am no expert in this area, so my fix may not be correct, but  it solves my build problem.  I hope it helps you.

**Comment by kechankrisna** [comment]
Please try new version, I just updated and tested for ios, android and macos

**Comment by mp035** [comment]
Just confirming, I tried it this afternoon (from pub dev) and it seems to be building and working ok.  (I only tested Android).  Thanks for such a prompt fix.  Have a great day.
